'use strict';
const ASSETS='../../../../assets/';
const LOGOS={opencode:'opencode.png',claude:'claude.png',codex:'openai.svg',gpt:'openai.svg',warp:'warp.png',github:'github.png',python:'python.png',pandas:'pandas.svg',plotly:'plotly.svg',n8n:'n8n.svg',nasa:'nasa.png',models:'models.svg',aa:'artificialanalysis.ico',ghostty:'ghostty.png',deepseek:'deepseek.svg',gemini:'google.svg'};
const logo=(name,label,cls='')=>'<img class="tool-logo '+cls+'" src="'+ASSETS+'logos/'+LOGOS[name]+'" alt="'+(label||name)+'">';
const chip=(name,label)=>'<span class="brand-chip">'+logo(name,label)+'<span>'+label+'</span></span>';
const link=(url,label,cls='text-link')=>'<a class="'+cls+'" href="'+url+'" target="_blank" rel="noopener noreferrer">'+label+' ↗</a>';
const tabs=(kind,items)=>'<div class="tabs" role="group">'+items.map((item,i)=>'<button data-'+kind+'="'+i+'" aria-pressed="'+(i===0)+'">'+item+'</button>').join('')+'</div>';
const make=(title,minutes,html,notes,sources,review,className='')=>({title,minutes,html,notes,sources,review,className});
const slides=[
make('IA para ingenieros y científicos',1,`
 <div class="cover-layout"><div><p class="course-name">AI for Engineers and Scientists</p><h1>IA para ingenieros<br>y <span class="gradient">científicos</span></h1><div class="session-title"><span class="eyebrow">Sesión 1</span><h2>¿Qué es realmente un LLM?</h2><p>Trabajar con agentes</p></div><div class="brand-row">${chip('opencode','OpenCode')}${chip('warp','Warp')}</div><p class="byline">Jean Pierre Mandujano <span>Cohorte 01 · DeepSkill</span></p></div>
 <div class="cover-result"><div class="result-head">${logo('nasa','NASA POWER')}<span>La práctica de hoy</span><i class="status-dot"></i></div><h2>Datos reales.<br>Una herramienta de ingeniería.</h2><div data-chart="cover"></div><div class="mini-stats"><span><strong>1.095</strong>datos diarios</span><span><strong>3</strong>ciudades</span><span><strong>2025</strong>año completo</span></div></div></div>`,
 'El nombre del curso es el protagonista. La sesión conserva el tema anunciado: qué es un LLM, con trabajo práctico con agentes. Dejar la portada mientras llegan. La apertura completa con JP y DeepSkill dura cinco minutos. El gráfico usa promedios reales de NASA POWER.',
 ['https://power.larc.nasa.gov/docs/tutorials/service-data-request/api/'],
 {idea:'Identificar el curso, el tema de hoy y la práctica.',interaction:'Curvas reales de NASA como anticipo de la demo.',focus:'Curso primero; tema de la sesión y trabajo con agentes como segundo nivel.'},'cover'),

make('Jean Pierre Mandujano',2,`
 <div class="profile-layout"><div class="profile-visual"><img class="portrait" src="${ASSETS}JeanPierre.webp" alt="Jean Pierre Mandujano"><span class="portrait-caption">Founder de DeepSkill</span></div><div class="profile-copy"><p class="eyebrow">Consultoría, arquitectura y dirección técnica</p><h1>Jean Pierre<br>Mandujano</h1><p class="profile-main">Lidero transformaciones de arquitectura y equipos de ingeniería en diferentes empresas.</p><div class="profile-lines"><p><span>Hoy</span>DeepSkill: proyectos y operación con agentes.</p><p><span>Formación</span>Coach ICPC y entrenamiento técnico.</p></div><div class="profile-links">${link('https://github.com/manduinca','GitHub / manduinca','profile-link')}${link('https://www.linkedin.com/in/jean-pierre-mandujano','LinkedIn','profile-link')}${link('https://www.deepskill.space/','DeepSkill','profile-link')}</div></div></div>`,
 'Presentar el trabajo actual como consultor de arquitectura y líder técnico, declarado por JP. Contar un problema de transformación y cómo lo resolvió. Foco en DeepSkill. Deep Pit queda como antecedente si surge en la conversación. No atribuir título universitario ni inventar nombres de clientes de consultoría.',
 ['https://www.deepskill.space/','https://github.com/manduinca','https://www.linkedin.com/in/jean-pierre-mandujano'],
 {idea:'Posicionar tu experiencia actual, con acceso a tus perfiles.',interaction:'Los enlaces abren GitHub, LinkedIn y la empresa.',focus:'Podemos precisar sectores o casos de consultoría que quieras contar.'},'profile-slide'),

make('DeepSkill: una empresa que trabaja con agentes',2,`
 <div class="company-title"><h1>DeepSkill</h1><p>Construimos software.<br><span class="gradient">Trabajamos con agentes.</span></p>${link('https://www.deepskill.space/','deepskill.space')}</div>
 <div class="company-layout"><div class="service-menu"><button data-service="0" aria-pressed="true"><span>01</span>Arquitectura y software</button><button data-service="1" aria-pressed="false"><span>02</span>IA y automatización</button><button data-service="2" aria-pressed="false"><span>03</span>Formación de talento</button></div><div class="service-detail" id="service-detail"></div></div>
 <div class="talent-strip"><span class="talent-label">Talento de<br><strong>DeepSkill</strong></span><figure><img src="${ASSETS}ElvisCapia.webp" alt="Elvis Capia"><figcaption>Elvis Capia<small>Coach ICPC</small></figcaption></figure><figure><img src="${ASSETS}RacsoGalvan.webp" alt="Racsó Galvan"><figcaption>Racsó Galvan<small>Finalista mundial ICPC</small></figcaption></figure><figure><img src="${ASSETS}EmanuelSoto.png" alt="Emanuel Soto"><figcaption>Emanuel Soto<small>Finalista mundial ICPC</small></figcaption></figure></div>`,
 'DeepSkill opera con agentes según JP. Se agrupan arquitectura, consultoría y desarrollo en una línea, con Minsur como cliente directo: DrillPlan Generator, generación de mallas y collars con visualización 3D. La fase 1 fue entregada; no presentar las mejoras propuestas de fase 2 como ejecutadas. Se mantienen Haul Sight co-desarrollado con IMSS, Python para Ingenieros en Cerro Verde vía Tecsup y entrenamientos en UNI. Seleccionar uno o dos casos dentro de la apertura.',
 ['https://www.deepskill.space/','https://www.deepskill.space/enterprise'],
 {idea:'Una presentación comercial concreta: servicios, casos y equipo.',interaction:'Seleccionar un servicio cambia el ejemplo y el proyecto de referencia.',focus:'Los casos ejecutados están separados de propuestas y de referencias de terceros.'},'company-slide'),

make('Qué es un LLM',3,`
 <h1>Qué es un LLM</h1><p class="slide-lead"><strong>Large Language Model:</strong> una red neuronal entrenada para trabajar con lenguaje y código.</p>
 <div class="training-strip"><span>Textos y código</span><i>→</i><span>Entrenamiento</span><i>→</i><strong>Parámetros aprendidos</strong></div>
 <div class="llm-machine" aria-label="Esquema conceptual de un LLM generativo basado en Transformer"><div class="machine-input"><span class="eyebrow">Tu contexto</span><div class="prompt-strip">Compara Lima y Arequipa</div><div class="mini-token-row"><span>Com</span><span>para</span><span> Lima</span><span> y</span><span> Arequipa</span></div><small>Texto → tokens → representaciones</small></div><span class="machine-arrow">→</span><div class="transformer-box"><span class="eyebrow">Arquitectura</span><h2>Transformer</h2><button data-transformer="attention" aria-pressed="true">Atención <span>Relacionar el contexto</span></button><span class="inner-arrow">↓</span><button data-transformer="layers" aria-pressed="false">Capas neuronales <span>Transformar representaciones</span></button></div><span class="machine-arrow">→</span><div class="machine-output"><span class="eyebrow">Generación</span><h3>Próximo token</h3><div class="possible-tokens"><span>La</span><span>Para</span><span>Los</span></div><p>Estima probabilidades<br>y produce una continuación.</p></div></div>
 <div class="transformer-caption" id="transformer-caption" aria-live="polite"></div>
 <p class="footnote">Entrenamiento: aprender parámetros. Inferencia: usarlos con tu contexto.</p>`,
 'Explicar LLM como modelo entrenado, no como aplicación. El diagrama muestra de forma conceptual un modelo generativo basado en Transformer, normalmente de tipo decoder. Atención relaciona representaciones de tokens dentro del contexto y las otras capas las transforman. No todas las redes de lenguaje tienen la misma arquitectura. El preentrenamiento causal aprende a predecir tokens; ajustes posteriores pueden mejorar seguimiento de instrucciones. Un pedido normal usa los parámetros, no vuelve a entrenar el modelo. Los fragmentos y candidatos mostrados son ilustrativos, sin tokenizador, pesos de atención ni inferencia real.',
 ['https://huggingface.co/learn/llm-course/chapter1/4','https://arxiv.org/abs/1706.03762'],
 {idea:'Entender el modelo y el papel del Transformer sin entrar en matemáticas.',interaction:'Seleccionar atención o capas cambia la explicación del diagrama.',focus:'Una arquitectura, un recorrido y la diferencia entre entrenar y usar el modelo.'},'llm-machine-slide'),

make('Tokens, generación y contexto',3,`
 <h1>Tokens, generación y contexto</h1><p class="slide-lead">El modelo genera una continuación a partir de lo que recibe en cada llamada.</p>
 <div class="llm-budget"><div class="generation-demo"><span class="eyebrow">Generación</span><h2>Un token a la vez</h2><p>Token: unidad de texto que procesa el modelo.</p><div class="generation-input">Contexto: compara los datos de NASA.</div><div class="token-stream" id="token-stream"></div><div><button class="action" id="token-next">Ver siguiente fragmento</button><button class="quiet" id="token-reset">Reiniciar</button></div><p class="example-label">Fragmentos ilustrativos; no son una tokenización real.</p></div><div class="context-budget"><span class="eyebrow">Ventana de contexto</span><h2>Cuánto puede recibir</h2><div class="context-capacities" role="group" aria-label="Capacidades ilustrativas de contexto"><button data-window="128000" aria-pressed="true">128K</button><button data-window="256000" aria-pressed="false">256K</button><button data-window="1000000" aria-pressed="false">1M</button></div><label class="context-files-label">Archivos añadidos <strong id="context-files-label"></strong><input id="context-files" type="range" min="0" max="1000000" step="4000" value="72000"></label><div class="context-budget-chart" id="context-budget-chart" role="img"></div><div class="budget-legend"><span><i class="instructions"></i>Instrucciones</span><span><i class="history"></i>Historial</span><span><i class="files"></i>Archivos</span><span><i class="tools"></i>Resultados</span><span><i class="reserve"></i>Salida reservada</span></div><p id="context-total"></p><p id="context-message" aria-live="polite"></p><small>Tamaños y presupuesto ilustrativos. Consulta el límite del modelo.</small></div></div>
 <p class="footnote">Más contexto permite incluir más información. Seleccionarlo bien también importa para la calidad y el coste.</p>`,
 'Mostrar tres fragmentos de generación y luego el presupuesto de contexto. K significa mil tokens y 1M un millón. Los tamaños son ejemplos, no especificaciones de un producto. Una llamada combina instrucciones, historial, archivos y resultados seleccionados por el arnés. La ventana limita lo que se puede procesar; el límite de salida también puede ser independiente y debe consultarse. El gráfico usa 2K de instrucciones, 18K de historial, 24K de resultados, archivos variables y reserva pedagógica de 8K para salida. No mide una conversación real. Subir archivos hasta exceder 128K, comparar 256K y 1M; seleccionar o resumir antes de enviar. Tener muchos archivos en disco no significa que todos estén en el contexto.',
 ['https://huggingface.co/learn/llm-course/chapter1/4','https://code.claude.com/docs/en/how-claude-code-works'],
 {idea:'Conectar generación, tokens y capacidad de contexto con decisiones de trabajo.',interaction:'Generar fragmentos; variar archivos y comparar 128K, 256K y 1M.',focus:'Separar archivos disponibles, contexto enviado y parámetros del modelo.'},'context-slide'),

make('Software y análisis con agentes',2,`
 <h1>Software y análisis con agentes</h1><p class="slide-lead">El cambio práctico: cuánto trabajo puedes delegar.</p>
 <div class="evolution-task"><span>El mismo objetivo</span><strong>Construir un reporte solar con datos de NASA</strong></div>
 <div class="evolution-track" role="group" aria-label="Formas de resolver la tarea"><button data-era="0" aria-pressed="false">Programación</button><button data-era="1" aria-pressed="false">LLM como asistente</button><button data-era="2" aria-pressed="true">Trabajo con agentes</button></div>
 <div class="delegation-track" id="delegation-track"></div><div class="delegation-result"><div><span class="eyebrow">Lo que delegamos</span><h2 id="era-title"></h2></div><div class="result-artifacts"><span>analysis.py</span><span>resumen.csv</span><span>reporte.html</span><small>Código y resultados que puedes revisar</small></div></div>
 <p class="footnote">Tú defines el objetivo, das contexto y compruebas la evidencia.</p>`,
 'Comparar con el mismo problema. En programación escribimos y ejecutamos los pasos. La asistencia con LLM propone código que la persona integra y ejecuta. Un agente conectado a herramientas puede inspeccionar, editar, ejecutar, observar y corregir. Esta capacidad permite encargar partes mayores del trabajo de software y análisis, conservando código y evidencia verificable. No elimina el criterio técnico. Son formas de trabajo que coexisten; un chat también puede dar acceso a un agente. El diagrama es conceptual y no ejecuta un modelo.',
 ['https://www.anthropic.com/engineering/building-effective-agents','https://code.claude.com/docs/en/how-claude-code-works'],
 {idea:'Mostrar por qué cambió la forma de construir software y analizar datos.',interaction:'Cambiar de modo mueve el trabajo entre la persona, el LLM y el agente.',focus:'Una tarea, responsabilidades visibles y resultados reproducibles.'},'evolution-slide'),

make('OpenCode: nuestro proyecto de trabajo',1,`
 <h1>${logo('opencode','OpenCode','heading-logo')}OpenCode</h1><div class="workspace-layout"><div><p class="big-copy">Abrimos una carpeta.<br>Elegimos un modelo.<br><span class="accent">Construimos y verificamos.</span></p><div class="workspace-options"><span>Desktop</span><span>Terminal</span><span>Editor</span></div>${link('https://opencode.ai/download','Descarga oficial','action-link')}<p class="example-label">Software gratuito. El coste de inferencia depende del modelo y del acceso elegido.</p></div><div class="project-window"><div class="browser-top"><i></i><i></i><i></i><span>Tu proyecto</span></div><div class="project-tree"><span class="folder">solar / starter</span><span>├── BRIEF.md</span><span>└── data /</span><span>　 ├── lima-2025.json</span><span>　 ├── arequipa-2025.json</span><span>　 ├── piura-2025.json</span><span>　 └── sources.json</span></div><div class="project-prompt"><span>Objetivo del agente</span>Inspecciona los datos, verifica las unidades y propón cómo construir la calculadora.</div></div></div>
 <p class="footnote">El agente recibe el problema y los datos. Nosotros revisamos las decisiones y el resultado.</p>`,
 'Pasar a OpenCode Desktop real. La ventana de la diapositiva representa el proyecto y el brief, no una captura de OpenCode. Abrir solo starter. Identificar proveedor y modelo disponible. La referencia está fuera de la carpeta. Falta ensayar la reconstrucción con el modelo gratuito elegido.',
 ['https://opencode.ai/download','https://opencode.ai/docs/models/','https://opencode.ai/docs/zen/'],
 {idea:'Dar una forma concreta de comenzar a trabajar.',interaction:'El brief y los archivos son los mismos de la demo.',focus:'La interfaz del proyecto es esquemática. La ejecución real se muestra en la app.'}),

make('Warp, shell y agentes de terminal',1,`
 <h1>${logo('warp','Warp','heading-logo')}Warp, shell y agentes</h1>
 <div class="terminal-layout"><div class="terminal-shell"><div class="terminal-title">${chip('warp','Warp')}<span>Secuencia ilustrativa de trabajo</span></div><pre id="terminal-output"></pre><button class="action" id="terminal-step">Ver siguiente comando</button><button class="quiet" id="terminal-reset">Reiniciar</button></div><div class="terminal-copy"><div class="terminal-layer"><span>Terminal</span><h2>Warp</h2><p>La superficie de trabajo.</p></div><div class="terminal-layer"><span>Shell</span><h2>zsh, bash, PowerShell</h2><p>Interpreta los comandos.</p></div><div class="terminal-layer"><span>Agentes</span><div class="brand-row">${chip('claude','Claude Code')}${chip('codex','Codex')}</div><p>También trabajan en terminal.</p></div><div class="warp-price-line"><div><span>Free · terminal</span><strong>USD 0</strong></div><div><span>Build · mensual</span><strong>USD 20/mes</strong></div><button id="warp-pricing">Planes y consumo ↗</button></div><p class="example-label">Consulta: 6 oct. 2026. Alternativas: Ghostty y Windows Terminal.</p></div></div>`,
 'Mostrar la secuencia ilustrativa y pasar a Warp. Terminal, shell y agente son capas distintas. Free incluye funciones básicas de terminal; Build mensual cuesta USD 20 e incluye USD 20 de consumo de agentes a tarifas de API, con consumo adicional de pago. La modalidad anual equivale a USD 18/mes con pago anual. Abrir el detalle de planes solo si surge la pregunta. Para usar OpenCode en la clase no es necesario contratar Warp Build.',
 ['https://www.warp.dev/pricing','https://docs.warp.dev/','https://ghostty.org/docs','https://learn.microsoft.com/en-us/windows/terminal/','https://code.claude.com/docs/en/overview','https://learn.chatgpt.com/docs/codex/cli'],
 {idea:'Mostrar una terminal como herramienta cotidiana.',interaction:'Recorrer comandos de un entorno virtual y ejecución.',focus:'El terminal dibujado es una secuencia educativa, no una sesión real.'}),

make('Chat, workflows y agentes',2,`
 <h1>Chat, workflows y agentes</h1><p class="slide-lead">Tres formas de resolver la misma tarea.</p>${tabs('flow-mode',['Chat','Workflow','Agente'])}
 <div class="comparison-products" id="comparison-products"></div><div class="flow-stage"><div class="flow-track" id="flow-track"></div><div class="flow-result"><span class="live-label">Ejemplo conceptual</span><h2 id="flow-title"></h2><p id="flow-description"></p><div class="flow-log" id="flow-log" aria-live="polite"></div></div></div>
 <div class="interaction-bar"><button class="action" id="flow-step">Ver siguiente paso</button><button class="quiet" id="flow-reset">Reiniciar</button><label class="check"><input id="flow-missing" type="checkbox">Faltan datos en la fuente</label></div>
 <p class="footnote">Un chat puede ser la interfaz de un agente. Un workflow puede contener pasos con LLM.</p>`,
 'Comparar formas de ejecución y no solo interfaces. El primer esquema es un chat de asistencia: devuelve una propuesta que la persona ejecuta. El workflow sigue un recorrido y reglas escritos previamente; n8n y un programa Python son ejemplos. El agente decide cómo continuar según objetivo y resultados dentro de sus permisos. Mostrar datos incompletos: pedir nueva información en chat, seguir una regla definida en workflow o investigar y proponer en agente. No afirmar que todos los chats son incapaces de actuar ni que el agente puede resolver cualquier problema. Los productos solo ilustran cada modalidad.',
 ['https://www.anthropic.com/engineering/building-effective-agents','https://docs.n8n.io/advanced-ai/examples/understand-tools'],
 {idea:'Diferenciar asistencia, recorrido programado y decisiones con herramientas.',interaction:'Tres modos, cuatro pasos y un caso de datos incompletos.',focus:'El criterio es quién dirige la ejecución; la interfaz por sí sola no define autonomía.'},'compare-slide'),

make('El agente y su arnés',2,`
 <h1>El agente y su arnés</h1><p class="slide-lead">Modelo, arnés y herramientas trabajan en un ciclo.</p>
 <div class="agent-objective"><span>Objetivo</span>Construye y verifica la calculadora solar.</div><div class="harness-layout"><button class="harness-node" data-harness="model">${logo('gpt','Modelo')}<strong>Modelo</strong><small>Propone la próxima acción</small></button><div class="connector-line"><span>contexto / decisión</span></div><button class="harness-core" data-harness="harness"><span class="eyebrow">Arnés · harness</span><h2>Coordina la ejecución</h2><div class="harness-chip-row">${chip('opencode','OpenCode')}${chip('codex','Codex')}</div><p>Sesión, contexto, herramientas y permisos.</p></button><div class="connector-line"><span>acción / resultado</span></div><div class="harness-tools"><button data-harness="files">Leer y editar archivos</button><button data-harness="terminal">Ejecutar programas</button><button data-harness="browser">Usar aplicaciones</button><button data-harness="permissions">Aplicar permisos</button></div></div>
 <div class="harness-explainer" id="harness-explainer" aria-live="polite"></div><p class="footnote">Los resultados vuelven al modelo para decidir cómo continuar.</p>`,
 'Relacionar la lámina con OpenCode ya abierto. El LLM produce texto o llamadas a herramientas; el arnés coordina su ejecución, devuelve resultados y prepara el contexto siguiente. Un agente incorpora este ciclo guiado por objetivo. Los permisos y herramientas disponibles determinan qué puede hacer. El control de navegador o aplicaciones gráficas requiere integración y entorno compatibles, no está garantizado por elegir cualquier arnés. Los cálculos los ejecuta el programa, no la predicción textual del modelo.',
 ['https://opencode.ai/docs/tools/','https://code.claude.com/docs/en/how-claude-code-works'],
 {idea:'Dar sentido al arnés usando el agente que ya mostramos.',interaction:'Seleccionar modelo, arnés, acciones o permisos muestra su función.',focus:'Distinguir decisiones del modelo de ejecución y observación de herramientas.'},'agent-slide'),

make('Configura tu agente',2,`
 <h1>Configura tu agente</h1><p class="slide-lead">Tres decisiones para preparar tu entorno de trabajo.</p>
 <div class="agent-choices"><button data-setup="model" aria-pressed="false"><span class="choice-number">01</span><h2>Elige el modelo</h2><div class="choice-brands">${chip('gpt','GPT')}${chip('claude','Claude')}${chip('deepseek','DeepSeek')}</div><p>Capacidad, contexto<br>y coste para tu tarea.</p></button><button data-setup="harness" aria-pressed="true"><span class="choice-number">02</span><h2>Elige el arnés</h2><div class="choice-brands">${chip('opencode','OpenCode')}${chip('claude','Claude Code')}${chip('codex','Codex')}</div><p>Herramientas, permisos<br>y forma de trabajar.</p></button><button data-setup="environment" aria-pressed="false"><span class="choice-number">03</span><h2>Elige el entorno</h2><div class="choice-environments"><span>⌘ <strong>Tu computador</strong></span><span>☁ <strong>Servidor / cloud</strong></span></div><p>Archivos, procesos<br>y acceso a recursos.</p></button></div>
 <div class="setup-explainer" id="setup-explainer" aria-live="polite"></div><p class="footnote">Para hoy: OpenCode Desktop, una carpeta local y un modelo disponible que comprobaremos con nuestra tarea.</p>`,
 'Usar las elecciones reales del participante. Modelo: proveedor, capacidad de herramientas, ventana y coste. Arnés: software que coordina el trabajo; puede tener varias interfaces. Entorno: dónde están los procesos, archivos y permisos. Un arnés local puede llamar a un modelo alojado remotamente. Las familias mostradas son ejemplos, no un ranking ni una promesa de compatibilidad con cualquier cuenta. Más adelante contrastar modelos con Artificial Analysis y explicar el acceso por API o plan. Evitar tratar Cloud como nombre de modelo o Warp como familia de modelos.',
 ['https://opencode.ai/docs/models/','https://opencode.ai/docs/','https://models.dev/'],
 {idea:'Convertir el mapa de productos en decisiones prácticas.',interaction:'Elegir una de las tres decisiones muestra qué comprobar.',focus:'Conectar cada nombre del mercado con una elección en el entorno.'},'setup-slide'),

make('Las herramientas del agente',2,`
 <h1>Las herramientas del agente</h1><p class="slide-lead">El arnés conecta al modelo con operaciones reales del computador.</p>
 <div class="workbench"><div class="computer-layers"><button data-tool="0" aria-pressed="false"><span class="layer-icon">⌘</span><div><strong>Sistema operativo</strong><small>Archivos, procesos, permisos</small></div></button><button data-tool="1" aria-pressed="false">${logo('warp','Aplicaciones')}<div><strong>Aplicaciones</strong><small>Terminal, intérprete, navegador</small></div></button><button data-tool="2" aria-pressed="true">${logo('pandas','Librerías y datos')}<div><strong>Librerías y datos</strong><small>pandas, Plotly, APIs públicas</small></div></button></div><div class="tool-preview" id="tool-preview"></div></div>
 <p class="footnote">Saber qué existe en tu entorno amplía lo que puedes pedir, ejecutar y verificar.</p>`,
 'Mostrar funciones concretas. El SO organiza archivos, procesos y permisos. Aplicaciones como terminal, Python y navegador ofrecen superficies de ejecución. Las librerías realizan operaciones: requests consulta una API, pandas agrupa y Plotly genera gráficos. NASA POWER es un servicio de datos remoto, no una librería ni un modelo. La herramienta del arnés invoca estas operaciones dentro del entorno autorizado. El control gráfico depende de una herramienta conectada; no asumirlo como capacidad nativa de todos los arneses. En la demo veremos crear entorno virtual, instalar dependencias y revisar una interfaz.',
 ['https://opencode.ai/docs/tools/','https://pandas.pydata.org/docs/','https://plotly.com/python/','https://power.larc.nasa.gov/docs/tutorials/service-data-request/api/'],
 {idea:'Explicar qué usa el agente para actuar, con el proyecto de clase.',interaction:'Cambiar SO, aplicaciones o librerías muestra una operación y su resultado.',focus:'Distinguir la llamada a una herramienta del programa o servicio que hace el trabajo.'},'tools-slide'),

make('Elegir modelo según la tarea',2,`
 <h1>Elegir modelo según la tarea</h1><div class="benchmark-layout"><div class="benchmark-copy">${chip('aa','Artificial Analysis')}<p class="big-copy">Capacidad,<br>velocidad<br>y <span class="accent">coste por tarea.</span></p><div class="metric-selector">${tabs('metric',['Capacidad','Velocidad','Coste'])}<p id="metric-explanation"></p></div>${link('https://artificialanalysis.ai/','Explorar los modelos','action-link')}${link('https://models.dev/','Models.dev')}</div><div class="browser-frame"><div class="browser-top"><i></i><i></i><i></i><span>artificialanalysis.ai</span></div><img id="benchmark-screen" src="${ASSETS}screens/aa-intelligence.png" alt="Gráfico real de inteligencia de Artificial Analysis"><div class="screen-caption">Captura del 6 oct. 2026. Abrimos los datos actuales en vivo.</div></div></div>
 <p class="footnote">El benchmark orienta. La elección se comprueba con nuestra tarea y nuestro arnés.</p>`,
 'Seleccionar dos métricas y abrir Artificial Analysis. Su captura es real, fechada, y no sustituye consultar los datos actuales. Diferenciar precio por token de coste de completar una tarea. Modelos de frontera, rápidos y con pesos abiertos se comparan por tarea y herramientas.',
 ['https://artificialanalysis.ai/','https://artificialanalysis.ai/methodology','https://models.dev/'],
 {idea:'Mostrar dónde comparar con un gráfico real del mercado.',interaction:'Cambiar la métrica explicada y abrir el análisis actual.',focus:'No congelar un ranking como recomendación universal.'}),

make('Qué cuesta una tarea con agentes',2,`
 <h1>Qué cuesta una tarea con agentes</h1><p class="slide-lead">Contexto y vueltas de trabajo se acumulan.</p>
 <div class="cost-layout"><div class="cost-controls"><label>Llamadas al modelo <strong id="cost-calls-label">10</strong><input id="cost-calls" type="range" min="1" max="30" value="10"></label><label>Entrada por llamada <strong id="cost-context-label">12.000 tokens</strong><input id="cost-context" type="range" min="1000" max="50000" step="1000" value="12000"></label><label class="check"><input id="cost-cache" type="checkbox" checked>50% de entrada leída de caché</label><p class="example-label">Tarifas ficticias por 1M tokens:<br>entrada $1, caché $0.20, salida $5.<br>1.200 tokens de salida por llamada.</p></div><div class="cost-display"><span class="eyebrow">Coste de esta tarea</span><output id="slide-cost-total">$0.132</output><div id="slide-cost-chart"></div></div></div>
 <div class="bottom-row"><p class="footnote">Tamaño constante por llamada. La calculadora completa permite cambiar las tarifas.</p>${link('../../../../tools/cost-calculator.html','Calculadora completa','action-link')}</div>`,
 'Mover llamadas de 10 a 20 y observar el doble de coste. Cambiar el contexto y desactivar caché. Las tarifas son ficticias. Este modelo no incluye crecimiento de historial ni escritura de caché, impuestos o herramientas. La salida incluye los tokens de razonamiento facturados por el proveedor.',
 ['https://artificialanalysis.ai/methodology','https://opencode.ai/docs/zen/'],
 {idea:'Hacer tangible el coste acumulado de una tarea.',interaction:'Sliders de llamadas y contexto, más caché.',focus:'Todos los importes de este ejemplo son ilustrativos.'}),

make('API, suscripción y modelo local',2,`
 <h1>API, suscripción y modelo local</h1><p class="slide-lead">El software, el modelo y el consumo se pagan de formas distintas.</p>
 <div class="access-selector">${tabs('access',['API','Suscripción','Oferta gratuita','Modelo local'])}</div><div class="access-stage" id="access-stage"></div>
 <p class="footnote">Las cuotas y compatibilidades se revisan en el proveedor y en el arnés elegido.</p>`,
 'Elegir API y suscripción para explicar la diferencia. Luego mostrar gratis y local. API y suscripción son contratos de acceso distintos. Las ofertas gratuitas cambian. Un modelo local requiere hardware y energía. Revisar tarifas oficiales en clase.',
 ['https://opencode.ai/docs/zen/','https://opencode.ai/go/','https://www.warp.dev/pricing','https://learn.chatgpt.com/pricing/','https://claude.com/pricing'],
 {idea:'Ordenar cómo se contrata y consume el modelo.',interaction:'Cuatro formas de acceso, cada una con su flujo y límites.',focus:'Una suscripción no es automáticamente crédito de API.'}),

make('Calculadora solar con NASA',1,`
 <div class="solar-heading"><h1>Una demanda.<br><span class="gradient">Tres recursos solares.</span></h1>${logo('nasa','NASA POWER')}</div>
 <div class="solar-layout"><div class="solar-control">${tabs('solar-city',['Lima','Arequipa','Piura'])}<label>Potencia nominal <strong id="solar-power-label">1.0 kWp</strong><input id="solar-power" type="range" min=".2" max="4" step=".1" value="1"></label><div class="solar-stat"><span>Producción anual estimada</span><strong id="solar-annual"></strong><small>kWh, con performance ratio 0.80</small></div>${link('../../../../demos/solar/reference/output/index.html','Abrir la herramienta completa','action-link')}</div><div class="solar-plot"><div class="plot-header"><h3>Producción media diaria por mes</h3><span>kWh/día</span></div><div data-chart="solar"></div><p class="example-label">La línea discontinua representa una demanda elegida de 3 kWh/día.</p></div></div>
 <p class="footnote">NASA POWER, 2025. Irradiación horizontal estimada. Potencia y rendimiento son supuestos.</p>`,
 'Cambiar ciudad o potencia durante treinta segundos y pasar a construir en el agente. Fuente real: 365 días por ciudad de 2025. Performance ratio 0.80 y demanda 3 son supuestos. No incluye inclinación, sombras ni almacenamiento. El gráfico calcula localmente sin llamar al modelo.',
 ['https://power.larc.nasa.gov/docs/tutorials/service-data-request/api/'],
 {idea:'Cerrar los conceptos con una herramienta real e interactiva.',interaction:'Cambiar ciudad y potencia con datos NASA archivados.',focus:'Los controles son el resultado de software que vamos a construir.'}),

make('Alternativas de demo',0,`
 <h1>Alternativas de demo</h1><p class="slide-lead">Una fuente pública y un problema concreto.</p>
 <div class="demo-options"><article>${logo('nasa','NASA')}<span class="option-number">01</span><h2>Recurso solar</h2><div class="demo-spark" data-chart="option-solar"></div><p>Ciudades, potencia y demanda.</p><small>NASA POWER, pandas, Plotly</small><span class="ready">Datos y referencia listos</span></article><article><span class="option-number">02</span><h2>Sismos y distancia</h2><div class="quake-chart" id="quake-preview"></div><p>Magnitud, profundidad y ubicación.</p><small>USGS, pandas, Plotly</small><span class="ready">Datos y brief listos</span></article><article><span class="option-number">03</span><h2>Rutas y redes</h2><div class="route-concept"><span>Origen</span><span class="route-line"></span><span>Destino</span></div><p>Rutas sobre una red vial.</p><small>OpenStreetMap, OSMnx, NetworkX</small><span class="pending">Pendiente de ensayo</span></article></div>`,
 'Apéndice opcional. Solar es la demo base. USGS tiene snapshot real de M4.5+ y brief, todavía sin herramienta terminada. La vista muestra la distribución real de magnitudes del snapshot. La ruta es un esquema de propuesta, no un cálculo ejecutado.',
 ['https://power.larc.nasa.gov/','https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php','https://osmnx.readthedocs.io/'],
 {idea:'Comparar opciones sin abrir tres demos durante la clase.',interaction:'Curvas solares y magnitudes reales del snapshot USGS.',focus:'Mantener una sola demo central.'}),

make('Revisar el trabajo del agente',0,`
 <h1>Revisar el trabajo del agente</h1><p class="slide-lead">Volvemos a la fuente y comprobamos un número.</p>
 <div class="verify-layout"><div class="source-record"><span class="eyebrow">NASA POWER, Lima</span><h2>1 de enero de 2025</h2><code id="verify-source"></code><small>Dato original: kWh/m²/día</small>${link('../../../../demos/solar/starter/data/lima-2025.json','Abrir la fuente')}</div><div class="verification-calc"><span class="eyebrow">Modelo educativo</span><p class="example-label">Horas solares equivalentes = irradiación / (1 kW/m²)</p><div class="calc-equation" id="verify-equation"></div><button class="action" id="verify-double">Duplicar potencia</button><div class="verify-check" id="verify-check"></div></div></div>
 <p class="footnote">La fuente aporta irradiación. Nosotros elegimos la potencia y el rendimiento.</p>`,
 'Comprobar el registro del 1 de enero y el cálculo con PR 0.80. Duplicar la potencia debe duplicar la producción en este modelo. Separar promedio mensual de total mensual, y cálculo anual de autonomía.',
 ['https://power.larc.nasa.gov/docs/tutorials/service-data-request/api/'],
 {idea:'Verificación mínima con una fuente y una relación matemática.',interaction:'Duplicar potencia y comprobar la proporcionalidad.',focus:'Una respuesta convincente no sustituye revisar unidades y cálculos.'}),

make('Materiales y lecturas para continuar',0,`
 <h1>Materiales y lecturas para continuar</h1><div class="reading-slide-layout"><div class="reading-slide-list"><span class="eyebrow">Tres lecturas de consulta</span><a href="https://www.anthropic.com/engineering/building-effective-agents" target="_blank" rel="noopener noreferrer">${logo('claude','Anthropic')}<div><h3>Building effective agents</h3><p>Patrones de workflows y agentes.</p></div><span>↗</span></a><a href="https://code.claude.com/docs/en/best-practices" target="_blank" rel="noopener noreferrer">${logo('claude','Claude Code')}<div><h3>Best practices for Claude Code</h3><p>Contexto, ejecución y verificación.</p></div><span>↗</span></a><a href="https://huggingface.co/learn/agents-course/en/unit0/introduction" target="_blank" rel="noopener noreferrer"><span class="hf-mark">🤗</span><div><h3>AI Agents Course</h3><p>Conceptos y ejercicios de Hugging Face.</p></div><span>↗</span></a></div><div class="materials-slide-panel"><span class="eyebrow">Tu espacio de práctica</span><h2>Datos, guías<br>y una biblioteca.</h2><p>Descargas de NASA y USGS, briefs legibles, documentación y costes con fuente.</p>${link('../../../../index.html','Abrir materiales','action-link')}<div class="materials-shortcuts">${link('../../../../downloads/solar-starter.zip','Demo solar · ZIP')}${link('../../../../index.html#costes','Warp y costes')}</div></div></div>
 <div class="company-cta"><div><strong>DeepSkill</strong><span>Arquitectura, software, IA y formación.</span></div>${link('https://www.deepskill.space/enterprise','Conversemos sobre tu equipo','action-link')}</div>`,
 'Abrir Materiales para mostrar la biblioteca y la descarga de la carpeta de práctica. La ruta de lectura distingue patrones base, práctica y ejercicios. Los enlaces de herramientas, modelos, datos y precios están organizados por propósito en el portal. Los ZIP contienen la tarea y los datos originales, sin la solución del instructor.',
 ['https://www.anthropic.com/engineering/building-effective-agents','https://code.claude.com/docs/en/best-practices','https://huggingface.co/learn/agents-course/en/unit0/introduction','https://www.deepskill.space/enterprise'],
 {idea:'Continuar con una ruta de lectura y materiales listos para practicar.',interaction:'Abrir la biblioteca, descargar la demo o consultar costes.',focus:'Mantener las lecturas de arquitectura y práctica separadas de los catálogos.'})
];
const previousTitles={'IA para ingenieros y científicos':'Trabajar con agentes','Tokens, generación y contexto':'Tokens, contexto y generación','Software y análisis con agentes':'LLMs, software y análisis de datos','Chat, workflows y agentes':'Workflow y agente','El agente y su arnés':'El arnés del agente','Configura tu agente':'Producto, interfaz y entorno','Las herramientas del agente':'Las herramientas del computador'};
slides.forEach((slide,i)=>{slide.previousTitle=previousTitles[slide.title];slide.appendix=slide.minutes===0;slide.chapter=i<3?'DeepSkill':i<6?'LLMs y contexto':i<8?'Entorno de trabajo':i<12?'Trabajar con agentes':i<15?'Modelos y costes':i===15?'Demo':'Recursos';});
