'use strict';
const stage=document.querySelector('#stage'),counter=document.querySelector('#counter'),overlay=document.querySelector('#overlay');let current=0;
slides.forEach((slide,i)=>{const section=document.createElement('section');section.className='slide '+(slide.className||'');section.hidden=true;section.setAttribute('aria-label',(i+1)+'. '+slide.title);section.innerHTML='<a class="brand" href="https://www.deepskill.space/" target="_blank" rel="noopener noreferrer"><img src="'+ASSETS+'deepskill.png" alt="">DeepSkill</a>'+slide.html;stage.append(section);});
function fit(){stage.style.setProperty('--scale',Math.max(.1,Math.min(innerWidth/1440,(innerHeight-76)/810)));}
function show(index,updateHash=true){current=Math.max(0,Math.min(slides.length-1,index));[...stage.children].forEach((el,i)=>el.hidden=i!==current);counter.textContent=(current+1)+' / '+slides.length;document.title=slides[current].title+' · DeepSkill';document.querySelector('#progress').style.width=(current+1)/slides.length*100+'%';document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;if(updateHash)history.replaceState(null,'','#s-'+(current+1));}
function fromHash(){const match=location.hash.match(/^#s-(\d+)$/);show(match?Number(match[1])-1:0,false);}
function notes(){const slide=slides[current],elapsed=slides.slice(0,current).reduce((sum,s)=>sum+s.minutes,0);document.querySelector('#overlay-content').innerHTML='<h2>'+slide.title+'</h2><p class="note-time">'+(slide.appendix?'Apéndice opcional':slide.minutes+' min · minuto '+elapsed+'–'+(elapsed+slide.minutes))+'</p><p>'+slide.notes+'</p>'+(slide.sources.length?'<h3>Fuentes</h3><ul>'+slide.sources.map(url=>'<li>'+link(url,url)+'</li>').join('')+'</ul>':'');overlay.showModal();}
function outline(){document.querySelector('#overlay-content').innerHTML='<h2>Diapositivas</h2><p class="muted">15 principales · 27 min · 3 apéndices opcionales</p>'+slides.map((s,i)=>'<button class="outline-item" data-slide="'+i+'"><span>'+(i+1)+'. '+s.title+'</span><small>'+(s.appendix?'Apéndice':s.minutes+' min')+'</small></button>').join('');overlay.showModal();}
function fullscreen(){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});}
document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelector('#notes').onclick=notes;document.querySelector('#outline').onclick=outline;document.querySelector('#fullscreen').onclick=fullscreen;overlay.querySelector('.close').onclick=()=>overlay.close();overlay.addEventListener('click',event=>{const target=event.target.closest('[data-slide]');if(target){show(Number(target.dataset.slide));overlay.close();}});
addEventListener('keydown',event=>{if(overlay.open||event.target.matches('input,textarea,select'))return;const key=event.key.toLowerCase();if(['arrowright','arrowdown',' ','pagedown'].includes(key)){event.preventDefault();show(current+1);}else if(['arrowleft','arrowup','pageup'].includes(key)){event.preventDefault();show(current-1);}else if(key==='home'){event.preventDefault();show(0);}else if(key==='end'){event.preventDefault();show(slides.length-1);}else if(key==='p')notes();else if(key==='o')outline();else if(key==='f')fullscreen();});addEventListener('hashchange',fromHash);addEventListener('resize',fit);fit();fromHash();

