'use strict';
const ASSETS='../../../../assets/';
const link=(url,label,cls='text-link')=>'<a class="'+cls+'" href="'+url+'" target="_blank" rel="noopener noreferrer">'+label+' ↗</a>';
const guide='../../../../materials/read.html?doc=session02-practice';
const sources={agents:'https://www.anthropic.com/engineering/building-effective-agents',mcp:'https://modelcontextprotocol.io/docs/learn/architecture',usgs:'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',rag:'https://www.anthropic.com/engineering/contextual-retrieval',embeddings:'https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',learn:'https://learn.microsoft.com/en-us/training/support/mcp',deepwiki:'https://docs.devin.ai/work-with-devin/deepwiki-mcp'};
const make=(title,minutes,chapter,html,notes,refs,review,className='',when='')=>({title,minutes,chapter,html,notes,sources:refs,review,className,when});
const slides=[
make('Del chat al agente',1,'Clase 2 · 8 octubre 2026',`
 <div class="opening"><div><p class="course-name">IA para ingenieros y científicos</p><h1>Del chat<br>al <span class="gradient">agente</span></h1><p class="opening-lead">Un objetivo, herramientas<br>y evidencia para avanzar.</p><p class="byline">Jean Pierre Mandujano <span>Cohorte 01 · DeepSkill</span></p></div>
 <div class="opening-diagram" aria-label="El agente actúa sobre un proyecto y usa los resultados para decidir"><div class="objective-line"><span>Objetivo de hoy</span><strong>5 sismos próximos a Lima</strong></div><div class="opening-orbit"><span class="orbit-top">Contexto</span><span class="orbit-left">Herramientas</span><div class="agent-center">Agente<small>decide el siguiente paso</small></div><span class="orbit-right">Resultados</span><span class="orbit-bottom">Verificación</span></div><p class="diagram-caption">Práctica con datos USGS</p></div></div>`,
 'Retomar el cierre de la primera clase: «grafica los datos» dejaba muchas decisiones abiertas. Hoy el grupo dirige una tarea concreta, observa las herramientas y comprueba el resultado. Dejar OpenCode listo desde la apertura. Completar la práctica antes del minuto 90. La última media hora se dedica a RAG conceptual, sin implementación.',[sources.agents],
 {idea:'Dirigir un trabajo que deja evidencia revisable.',interaction:'La tarea USGS conecta todas las explicaciones.',focus:'Portada breve. Abrir OpenCode y la carpeta de trabajo.'},'session-cover','0–5 min · apertura'),

make('El contexto de una tarea',5,'Contexto',`
 <h1>El contexto de una tarea</h1><p class="slide-lead">La información que llega al modelo orienta sus decisiones.</p>
 <div class="context-layout"><div class="prompt-side"><span class="eyebrow">El pedido</span><blockquote id="context-prompt">«Grafica los sismos.»</blockquote><button class="action" id="context-toggle" aria-pressed="false">Precisar el pedido</button><p class="small-note" id="context-explanation">¿Qué datos, qué gráfico y cómo sabremos si está bien?</p></div>
 <div class="context-composition" aria-label="Componentes del contexto"><div><span class="context-mark">01</span><h2>Objetivo</h2><p>Encontrar los 5 eventos más próximos a Lima.</p></div><div><span class="context-mark">02</span><h2>Datos pertinentes</h2><p>GeoJSON, procedencia y documentación de campos.</p></div><div><span class="context-mark">03</span><h2>Restricciones</h2><p>Conservar los originales. Registrar unidades y método.</p></div><div><span class="context-mark">04</span><h2>Criterio de aceptación</h2><p>Tabla ordenada, distancias en km y CSV verificable.</p></div></div></div>
 <div class="slide-bottom"><p>Las instrucciones del usuario, los documentos y los resultados de herramientas cumplen funciones distintas.</p><span>Una carpeta disponible se incorpora mediante lecturas y selección.</span></div>`,
 'Preguntar qué falta en el pedido inicial antes de pulsar Precisar. La versión completa incluye Lima (-12.0464, -77.0428), cinco resultados, Haversine y salida verificable. Contexto es lo que recibe el modelo en una llamada: instrucciones, conversación, descripciones de herramientas y contenido seleccionado. Tener un archivo en disco no implica que el modelo haya recibido todo su contenido. Los documentos consultados son fuentes de información, no autorización para ejecutar sus instrucciones. En OpenCode, pedir inspección y plan antes de construir. El usuario revisa el plan porque así está planteado el ejercicio.',[sources.agents,sources.usgs],
 {idea:'Convertir un pedido general en un resultado que se puede comprobar.',interaction:'Alternar entre el pedido inicial y el brief preciso.',focus:'Distinguir contexto recibido, archivos disponibles e instrucciones.'},'','5–20 min · explicación y primer pedido'),

make('El ciclo del agente',5,'Agente',`
 <h1>El ciclo del agente</h1><p class="slide-lead">El modelo decide. El entorno ejecuta. El resultado informa la siguiente decisión.</p>
 <div class="agent-layout"><div class="agent-cycle"><div class="cycle-step active" data-cycle="0"><span>1</span><strong>Decidir</strong><small>Elegir una acción</small></div><div class="cycle-step" data-cycle="1"><span>2</span><strong>Actuar</strong><small>Invocar una herramienta</small></div><div class="cycle-step" data-cycle="2"><span>3</span><strong>Observar</strong><small>Leer el resultado</small></div><div class="cycle-step" data-cycle="3"><span>4</span><strong>Revisar</strong><small>Continuar o terminar</small></div><span class="cycle-return">El resultado vuelve al contexto</span></div>
 <div class="trace-example" aria-live="polite"><span class="eyebrow">Ejemplo ilustrativo</span><h2 id="trace-title">Necesito conocer los datos</h2><p id="trace-description">El agente elige leer la estructura del GeoJSON antes de calcular.</p><pre id="trace-code">Acción propuesta: leer archivo</pre><div class="trace-controls"><button class="action" id="trace-next">Siguiente paso</button><button class="quiet" id="trace-reset">Reiniciar</button></div></div></div>
 <div class="slide-bottom"><p>Los permisos y las condiciones de cierre delimitan el trabajo.</p><span>Secuencia local preparada para explicar el ciclo. No ejecuta un LLM.</span></div>`,
 'Recorrer los cuatro pasos con el botón. El ejemplo está guionado, no representa una ejecución real ni un registro interno del modelo. El programa de cálculo lo escribe o selecciona el agente y lo ejecuta una herramienta del entorno. Las observaciones incluyen resultados y errores. Una nueva decisión puede corregir la lectura de campos, ejecutar otra herramienta o terminar si se cumple el criterio. Contrastar con una secuencia fija: aquí las observaciones influyen en las acciones que decide el modelo. Ir a OpenCode y señalar una llamada y su resultado real. No pedir razonamiento interno del modelo. Observar acciones, argumentos y evidencias.',[sources.agents],
 {idea:'Un agente toma decisiones usando resultados del entorno.',interaction:'Avanzar una secuencia ilustrativa y compararla con la ejecución real.',focus:'Distinguir decisión del modelo de ejecución de la herramienta.'},'','20–35 min · observar el trabajo en OpenCode'),

make('Herramientas y conexiones',5,'Herramientas · API · MCP',`
 <h1>Herramientas y conexiones</h1><p class="slide-lead">Una operación puede llegar al sistema por distintas interfaces.</p>
 <div class="connection-tabs" role="group" aria-label="Forma de conexión"><button data-connection="local" aria-pressed="true">Archivos y programas</button><button data-connection="api" aria-pressed="false">API HTTP</button><button data-connection="nasa" aria-pressed="false">API con clave</button><button data-connection="mcp" aria-pressed="false">MCP público</button><button data-connection="oauth" aria-pressed="false">MCP + OAuth</button></div>
 <div id="connection-diagram" class="connection-diagram" aria-live="polite"></div>
 <div class="connection-detail"><div><h2 id="connection-title"></h2><p id="connection-description"></p></div><pre id="connection-code"></pre></div>
 <div class="connection-footer"><p><strong>API key</strong> es una credencial de acceso. Un servicio puede exigirla o ser público.</p><a id="connection-source" target="_blank" rel="noopener noreferrer">Documentación ↗</a></div>`,
 'Usar las tres pestañas con ejemplos concretos. Local: la herramienta ejecuta un programa que lee el archivo. API: una interfaz permite pedir datos mediante HTTP y recibir GeoJSON; USGS no exige clave en este ejemplo. MCP: el host de IA integra un cliente MCP, descubre capacidades del servidor e invoca sus herramientas. El servidor puede llamar a otra API, leer archivos o consultar una base de datos. MCP y API no son alternativas excluyentes, y API key es una credencial en otro nivel. Mostrar DeepWiki como demo pública sin autenticación: conectar en el cliente disponible, revisar herramientas y preguntar por el soporte de GeoJSON de un repositorio público comprobado, por ejemplo Leaflet/Leaflet. Microsoft Learn queda como alternativa para consultar cómo importar un CSV con Power Query. Everything permite mostrar el contraste con autorización OAuth con identidad ficticia, sin cuenta propia. Los nombres concretos de herramientas se toman de la lista descubierta en vivo. La presentación solo dibuja estas conexiones y enlaza fuentes; no llama al servidor. Si el cliente o la red no están listos, mostrar el esquema y continuar con la API pública. La pestaña API con clave muestra NASA NeoWs con DEMO_KEY, una clave pública para pruebas con límites reducidos. No es una clave privada ni necesita registro para ese ejemplo. La consulta real, si se hace, debe conservar respuesta y procedencia aparte. La configuración profunda de software, HTTP y credenciales se retoma en clase 3.',[sources.mcp,sources.deepwiki,sources.learn,'https://earthquake.usgs.gov/fdsnws/event/1/','https://developer.mozilla.org/en-US/docs/Glossary/API','https://api.nasa.gov/assets/html/authentication.html'],
 {idea:'Distinguir interfaz, protocolo y credencial.',interaction:'Comparar archivos, API pública, API con clave y MCP; luego mostrar la conexión real.',focus:'MCP puede envolver una API. La clave responde quién puede acceder.'},'','35–50 min · API y demo MCP del docente'),

make('Cinco sismos más próximos a Lima',4,'Práctica · OpenCode',`
 <h1>Cinco sismos más próximos a Lima</h1><p class="slide-lead">Una entrega revisable: tabla, distancia documentada y archivo CSV.</p>
 <div class="practice-layout"><div class="practice-brief"><ol><li><strong>Inspeccionar</strong><span>Campos, unidades y procedencia.</span></li><li><strong>Planear y construir</strong><span>Ordenar por distancia al punto elegido.</span></li><li><strong>Comprobar</strong><span>Recalcular un evento y revisar el CSV.</span></li></ol><div class="practice-links"><a class="action-link" href="${guide}" target="_blank" rel="noopener noreferrer">Abrir la práctica ↗</a><a href="../../../../downloads/earthquakes-starter.zip" download>Carpeta inicial · ZIP ↓</a></div><button class="quiet copy-prompt" id="copy-prompt">Copiar primer pedido</button><span class="copy-status" id="copy-status" role="status"></span></div>
 <div class="evidence-view"><div class="evidence-heading"><span>Referencia docente · cálculo local</span><label>Punto <select id="quake-city" aria-label="Punto de referencia"><option value="lima">Lima</option><option value="arequipa">Arequipa</option><option value="piura">Piura</option></select></label></div><div id="quake-plot" class="quake-plot"></div><div id="quake-table" aria-live="polite">Cargando el catálogo archivado…</div></div></div>
 <div class="slide-bottom practice-bottom"><p id="quake-provenance">Snapshot USGS del 6 oct. 2026 · M4.5+ · distancia superficial Haversine, R = 6371 km.</p><span>El catálogo describe eventos registrados. No estima peligro ni predice sismos.</span></div>`,
 'Mantener esta lámina mientras el grupo trabaja. Los cuatro minutos son la explicación del brief; la práctica continúa en OpenCode hasta el minuto 80. Abrir solo demos/earthquakes/starter en el agente del alumno, fuera de las referencias docentes. La guía de clase 2 acota el brief amplio al top 5 y CSV; el mapa queda como extensión. El selector de esta referencia ejecuta Haversine localmente sobre el snapshot original. Es una proyección cartesiana de latitud/longitud con datos reales, no una cartografía de distancias. La distancia ordena epicentros y no incorpora profundidad. Confirmar coordenadas GeoJSON [longitud, latitud, profundidad_km], fechas UTC, nulos e IDs. El valor de Lima es -12.0464, -77.0428. Aceptar diferencias de redondeo o un método geodésico documentado. Si consultan la API en vivo, guardar su respuesta y su procedencia aparte; no comparar un catálogo nuevo con los valores del snapshot como si fueran iguales. Cerrar con evidencia y descansar del 80 al 90.',[sources.usgs,'https://earthquake.usgs.gov/fdsnws/event/1/'],
 {idea:'Dirigir una tarea y comprobar qué produjo el agente.',interaction:'Guía, pedido copiable y referencia numérica sobre datos reales.',focus:'La referencia está fuera del starter. La práctica termina antes de RAG.'},'','50–90 min · práctica, revisión y descanso'),

make('Cuando crece el volumen documental',2,'RAG · cierre conceptual',`
 <h1>Cuando crece el volumen documental</h1><p class="slide-lead">¿Qué información conviene llevar al contexto de cada consulta?</p>
 <div class="corpus-layout"><div><div class="corpus-field" aria-hidden="true">${Array.from({length:48},(_,i)=>'<i class="document-tile '+(i%13===0?'selected':'')+'"></i>').join('')}</div><p class="diagram-caption">Manuales, informes, procedimientos y versiones</p></div><div class="corpus-question"><p class="question-text">«¿Qué procedimiento aplica<br>a este equipo?»</p><div class="reading-choice"><span>Leer todo repetidamente</span><p>Puede aumentar el contenido procesado, las llamadas y el tiempo.</p></div><div class="reading-choice selected"><span>Recuperar contenido pertinente</span><p>Seleccionar evidencia para la consulta y conservar su origen.</p></div></div></div>
 <div class="slide-bottom"><p>Un agente puede buscar y citar archivos. La recuperación añade una estrategia de acceso al corpus.</p><span>Diagrama conceptual. Sin cifras de consumo ni llamada a un modelo.</span></div>`,
 'Este bloque comienza en el minuto 90, con la práctica cerrada. Plantear qué cambia si los archivos se multiplican a miles de documentos. No afirmar que un agente siempre lee todos los archivos ni que los bytes en disco consumen tokens por sí mismos. El coste depende de los fragmentos enviados, llamadas, caché, búsqueda y preparación. Leer exhaustivamente y repetidamente puede resultar caro y lento; la recuperación ayuda a seleccionar evidencia. Los agentes también pueden buscar y registrar referencias sin un índice RAG. Evitar la promesa de ahorro automático o precisión garantizada. Conectar con documentación de una planta o procedimientos técnicos, sin realizar una búsqueda real ni construir un índice.',[sources.rag,sources.agents],
 {idea:'El volumen documental exige decidir qué contenido recuperar.',interaction:'Conversación sobre un corpus técnico, sin práctica.',focus:'Introducir el problema antes de nombrar la arquitectura.'},'','90–96 min · conversación conceptual'),

make('Embeddings y similitud semántica',4,'RAG · búsqueda por significado',`
 <h1>Embeddings y similitud semántica</h1><p class="slide-lead">Un modelo convierte texto en un vector de números.</p>
 <div class="embedding-transform" aria-label="El mismo modelo de embeddings transforma la pregunta y los fragmentos en vectores comparables"><div><strong>Pregunta / fragmento</strong><small>Texto</small></div><span class="flow-connector" aria-hidden="true"></span><div><strong>Modelo de embeddings</strong><small>Representación aprendida</small></div><span class="flow-connector" aria-hidden="true"></span><div><strong>Vector</strong><code>[0.12, −0.48, …]</code></div></div>
 <div class="embedding-layout"><figure class="semantic-figure"><svg viewBox="0 0 720 300" role="img" aria-labelledby="semantic-title semantic-description"><title id="semantic-title">Textos relacionados en un espacio ilustrativo</title><desc id="semantic-description">La pregunta La bomba no entrega agua se dibuja cerca de Sin caudal en la descarga y Falla de bombeo. Catálogo de bombas aparece separado. Las posiciones son inventadas para explicar similitud, no resultados de un modelo.</desc><ellipse class="semantic-region" cx="245" cy="163" rx="205" ry="115"/><path class="semantic-link" d="M180 170L290 88M180 170L365 245"/><circle class="semantic-query" cx="180" cy="170" r="11"/><text class="semantic-query-label" x="60" y="214">La bomba no entrega agua</text><text class="semantic-kind" x="60" y="240">PREGUNTA</text><circle class="semantic-fragment" cx="290" cy="88" r="9"/><text x="170" y="55">Sin caudal en la descarga</text><circle class="semantic-fragment" cx="365" cy="245" r="9"/><text x="350" y="280">Falla de bombeo</text><circle class="semantic-other" cx="590" cy="135" r="9"/><text class="semantic-other-label" x="480" y="100">Catálogo de bombas</text></svg><figcaption>Espacio ilustrativo en 2D · posiciones y vector inventados</figcaption></figure><div class="semantic-takeaway"><p>Palabras distintas.<br><strong>Significado relacionado.</strong></p><span>Comparar vectores → recuperar fragmentos</span></div></div>
 <div class="slide-bottom"><p>La similitud ayuda a buscar. No demuestra que un texto sea verdadero.</p><span>Un embedding real puede tener cientos de dimensiones.</span></div>`,
 'Definir embedding como representación numérica aprendida de un texto. Un modelo de embeddings se entrena para que ciertas relaciones entre textos se reflejen en la similitud de sus vectores; en modelos de frases puede usarse entrenamiento con pares relacionados y no relacionados. Durante la preparación del corpus se representan los fragmentos; al consultar se representa la pregunta en un espacio compatible, normalmente con el mismo modelo y las instrucciones apropiadas para documentos y consultas. Comparar no significa buscar solo palabras idénticas: «La bomba no entrega agua» y «Sin caudal en la descarga» expresan ideas relacionadas. «Catálogo de bombas» comparte una palabra pero responde a otra intención. El dibujo y los números están construidos a mano: no son una proyección de embeddings reales ni una medición de similitud. Los ejes no representan conceptos definidos. En un sistema real puede utilizarse similitud coseno: producto escalar dividido entre las normas, que compara la dirección de los vectores. No hace falta mostrar la fórmula en pantalla. Una puntuación no es una probabilidad ni una garantía de verdad; incluso textos contradictorios pueden ser semánticamente próximos. Se recuperan los fragmentos originales y sus metadatos, no solo los vectores, para dar evidencia al LLM. Explicar que el modelo de embeddings y el modelo generativo cumplen funciones diferentes. RAG puede usar búsqueda léxica o híbrida; los embeddings explican la variante semántica, no son un requisito de toda arquitectura RAG. Para códigos, nombres y versiones exactas conviene complementar con coincidencia léxica y filtros. Adaptación del bloque conceptual de EscuelaIT: texto a vector, similitud y dos fases del RAG; sin trasladar su práctica ni sus cifras.',[sources.embeddings,sources.rag],
 {idea:'Los embeddings permiten comparar textos por relaciones aprendidas de significado.',interaction:'Señalar la pregunta, los fragmentos cercanos y el texto con otra intención.',focus:'Gráfico didáctico; similitud no implica verdad y RAG no exige búsqueda vectorial.'},'embedding-slide','96–108 min · embeddings y similitud'),

make('RAG: recuperación y generación',4,'RAG · arquitectura',`
 <h1>RAG: recuperación y generación</h1><p class="slide-lead">Retrieval-Augmented Generation · Generación aumentada por recuperación</p>
 <div class="rag-preparation"><span class="rag-label">Preparación del corpus</span><div class="rag-node"><strong>Documentos</strong><small>Versiones y fuentes</small></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node"><strong>Fragmentos</strong><small>Texto + origen</small></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node"><strong>Embeddings</strong><small>Vectores de los fragmentos</small></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node"><strong>Índice</strong><small>Vectores, texto y origen</small></div></div>
 <div class="rag-query"><span class="rag-label">Ante una consulta</span><div class="rag-path"><div class="rag-node"><strong>Pregunta</strong></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node"><strong>Embedding</strong><small>Espacio compatible</small></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node retrieval"><strong>Recuperación</strong><small>Fragmentos originales</small></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node"><strong>LLM</strong><small>Pregunta + evidencia</small></div><span class="flow-connector" aria-hidden="true"></span><div class="rag-node answer"><strong>Respuesta</strong><small>Referencias revisables</small></div></div></div>
 <div class="rag-evidence"><span>Origen conservado</span><code>manual.pdf · versión 3 · página 42 · fragmento 8</code><p>El sistema debe conservar estas referencias y comprobar que respaldan la respuesta.</p></div>
 <div class="slide-bottom"><p>Un agente puede usar RAG como herramienta para consultar conocimiento.</p><span>Variante semántica ilustrada. También existe recuperación léxica o híbrida.</span></div>`,
 'Recorrer la variante semántica dibujada en dos fases. Preparación: obtener documentos, dividir con criterio, preservar versiones y metadatos, crear embeddings de los fragmentos e indexar sus vectores junto con el texto original o referencias para recuperarlo. Consulta: representar la pregunta en un espacio compatible, comparar con el índice, recuperar fragmentos originales, incorporar la pregunta y evidencia al contexto del modelo generativo, generar y verificar la respuesta y sus referencias. El índice puede ser léxico, vectorial o híbrido; RAG no exige por definición una base de datos vectorial. Las etapas y los metadatos mostrados son una arquitectura conceptual, no un sistema funcionando. El ejemplo manual.pdf es ficticio. Citas, control de versiones, cobertura y permisos deben diseñarse, no aparecen automáticamente. El agente puede decidir consultar el recuperador dentro de su ciclo. RAG recupera conocimiento durante la consulta y no equivale a reentrenar el modelo. Dedicar el tiempo restante a preguntas: ¿qué pasa si no aparece evidencia?, ¿si el manual está desactualizado?, ¿si dos fuentes discrepan? No implementar RAG en esta sesión.',[sources.rag,sources.agents],
 {idea:'RAG recupera evidencia y la incorpora al contexto de generación.',interaction:'Recorrer preparación y consulta con un diagrama editable.',focus:'Fuentes, versiones, cobertura y verificación; sin implementación.'},'','108–120 min · arquitectura y preguntas')
];
