'use strict';
(() => {
 const $=s=>document.querySelector(s);
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const precise='Encuentra los 5 sismos del catálogo más próximos a Lima (-12.0464, -77.0428). Entrega una tabla y un CSV con ID, magnitud, profundidad y distancia en km. Documenta Haversine y conserva los datos originales.';
 $('#context-toggle').onclick=()=>{
  const expanded=$('#context-toggle').getAttribute('aria-pressed')!=='true';
  $('#context-toggle').setAttribute('aria-pressed',String(expanded));$('#context-toggle').textContent=expanded?'Volver al pedido inicial':'Precisar el pedido';
  $('#context-prompt').textContent=expanded?precise:'«Grafica los sismos.»';$('.prompt-side').classList.toggle('expanded',expanded);
  $('#context-explanation').textContent=expanded?'Podemos revisar la entrega contra un criterio explícito.':'¿Qué datos, qué gráfico y cómo sabremos si está bien?';
 };
 const trace=[
  ['Necesito conocer los datos','El agente elige leer la estructura del GeoJSON antes de calcular.','Acción propuesta: leer archivo'],
  ['La herramienta lee el archivo','El entorno ejecuta la lectura solicitada y devuelve contenido.','Herramienta: lector de archivos\nEntrada: data/usgs-m45-month.geojson'],
  ['La respuesta aporta evidencia','El agente recibe campos y unidades para preparar el cálculo.','coordinates: [longitud, latitud, profundidad]\ntime: milisegundos Unix'],
  ['La siguiente decisión cambia','Con esta información puede calcular, comprobar y continuar hasta cumplir el objetivo.','Siguiente acción: ejecutar el cálculo\nCierre: tabla + CSV + evidencia']
 ];let step=0;
 function paintTrace(){document.querySelectorAll('[data-cycle]').forEach(n=>n.classList.toggle('active',Number(n.dataset.cycle)===step));$('#trace-title').textContent=trace[step][0];$('#trace-description').textContent=trace[step][1];$('#trace-code').textContent=trace[step][2];$('#trace-next').textContent=step===3?'Recorrer otra vez':'Siguiente paso';}
 $('#trace-next').onclick=()=>{step=(step+1)%4;paintTrace();};$('#trace-reset').onclick=()=>{step=0;paintTrace();};
 const connections={
  local:{nodes:[['Agente','decide leer o calcular'],['Herramienta local','lectura o ejecución'],['Archivo / programa','GeoJSON, CSV, Python']],title:'El trabajo ocurre en el entorno local',description:'La herramienta accede al archivo o ejecuta un programa con los permisos disponibles.',code:'leer: data/usgs-m45-month.geojson\nejecutar: programa de distancias\nguardar: cinco_sismos.csv',source:'https://www.anthropic.com/engineering/building-effective-agents'},
  api:{nodes:[['Agente','elige la consulta'],['Cliente HTTP','envía la petición'],['API de USGS','devuelve GeoJSON']],title:'Una API ofrece operaciones a otros programas',description:'En este ejemplo, una petición HTTP obtiene datos estructurados desde un servidor público.',code:'GET https://earthquake.usgs.gov/\n  earthquakes/feed/v1.0/summary/4.5_month.geojson\n\nRespuesta: GeoJSON · sin API key',source:'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php'},
  nasa:{nodes:[['Agente','elige la consulta'],['Cliente HTTP','incluye una credencial'],['API NASA NeoWs','datos de asteroides']],title:'La credencial acompaña la petición',description:'DEMO_KEY es una clave pública de prueba de NASA. Tiene límites de uso reducidos y permite explicar el acceso sin crear cuentas.',code:'https://api.nasa.gov/neo/rest/v1/feed\n\nstart_date=AAAA-MM-DD\napi_key=DEMO_KEY  (clave pública de prueba)',source:'https://api.nasa.gov/assets/html/authentication.html'},
  oauth:{nodes:[['Cliente MCP','solicita acceso'],['Autorización OAuth','consentimiento de prueba'],['Servidor MCP','Everything · datos ficticios']],title:'OAuth autoriza el acceso a las herramientas',description:'El cliente abre una pantalla de consentimiento y obtiene un token de acceso. La demo oficial usa una identidad ficticia y no requiere una cuenta propia.',code:'https://example-server.modelcontextprotocol.io/mcp\n\nConectar · aprobar consentimiento\nDescubrir herramientas · invocar una',source:'https://github.com/modelcontextprotocol/inspector/blob/main/docs/mcp-server-configuration.md'},
  mcp:{nodes:[['Aplicación de IA','agente + cliente MCP'],['Servidor MCP','DeepWiki · sin autenticación'],['Documentación','repositorios públicos']],title:'MCP permite descubrir e invocar herramientas',description:'El cliente descubre las herramientas. El agente puede preguntar cómo una librería trabaja con GeoJSON y usar esa información en el proyecto.',code:'https://mcp.deepwiki.com/mcp\n\nHerramientas: read_wiki_structure\nread_wiki_contents · ask_question',source:'https://docs.devin.ai/work-with-devin/deepwiki-mcp'}
 };
 function connection(key){const c=connections[key];document.querySelectorAll('[data-connection]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.connection===key)));$('#connection-diagram').innerHTML=c.nodes.map(n=>'<div class="connection-node"><strong>'+n[0]+'</strong><small>'+n[1]+'</small></div>').join('<span class="flow-connector" aria-hidden="true"></span>');$('#connection-title').textContent=c.title;$('#connection-description').textContent=c.description;$('#connection-code').textContent=c.code;$('#connection-source').href=c.source;}
 document.querySelectorAll('[data-connection]').forEach(b=>b.onclick=()=>connection(b.dataset.connection));connection('local');
 const firstPrompt='Lee BRIEF.md, data/sources.json y la estructura de data/usgs-m45-month.geojson. Para esta clase acotaremos la tarea a los cinco eventos del catálogo más próximos a Lima (-12.0464, -77.0428), una tabla y un CSV. Identifica campos, unidades, nulos y orden de coordenadas. Propón el cálculo de distancia superficial Haversine con radio de 6371 km y un plan de verificación. Conserva los originales. Espera mi revisión del plan antes de construir.';
 $('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText(firstPrompt);$('#copy-status').textContent='Pedido copiado.';}catch{$('#overlay-content').innerHTML='<h2>Primer pedido</h2><p>'+escape(firstPrompt)+'</p>';$('#overlay').showModal();$('#copy-status').textContent='Selecciona el pedido en la ventana.';}};
 const cities={lima:{name:'Lima',lat:-12.0464,lon:-77.0428},arequipa:{name:'Arequipa',lat:-16.4090,lon:-71.5375},piura:{name:'Piura',lat:-5.1945,lon:-80.6328}};
 const dataRoot='../../../../demos/earthquakes/starter/data/';let catalog;
 function plot(nearest,point){
  const x=lon=>45+(lon+86)/21*480,y=lat=>190-(lat+25)/30*170;
  const grid=[-85,-80,-75,-70,-65].map(l=>'<line x1="'+x(l)+'" x2="'+x(l)+'" y1="20" y2="190" stroke="#4d7fff20"/><text x="'+x(l)+'" y="209" text-anchor="middle">'+l+'°</text>').join('')+[-25,-15,-5,5].map(l=>'<line x1="45" x2="525" y1="'+y(l)+'" y2="'+y(l)+'" stroke="#4d7fff20"/><text x="38" y="'+(y(l)+4)+'" text-anchor="end">'+l+'°</text>').join('');
  const dots=catalog.features.filter(f=>{const c=f.geometry?.coordinates;return c&&c[0]>=-86&&c[0]<=-65&&c[1]>=-25&&c[1]<=5;}).map(f=>'<circle cx="'+x(f.geometry.coordinates[0])+'" cy="'+y(f.geometry.coordinates[1])+'" r="3" fill="#4d7fff" opacity=".55"/>').join('');
  const selected=nearest.map((e,i)=>'<g><title>'+escape(e.id+' · '+e.distance.toFixed(1)+' km')+'</title><line x1="'+x(point.lon)+'" y1="'+y(point.lat)+'" x2="'+x(e.lon)+'" y2="'+y(e.lat)+'" stroke="#99ff3240"/><circle cx="'+x(e.lon)+'" cy="'+y(e.lat)+'" r="5" fill="#99ff32"/><text x="'+(x(e.lon)+(i===4?-12:9))+'" y="'+(y(e.lat)+(i===4?18:-7))+'" style="fill:#99ff32">'+(i+1)+'</text></g>').join('');
  $('#quake-plot').innerHTML='<svg viewBox="0 0 560 230" role="img" aria-label="Eventos registrados en una vista regional de longitud y latitud. Verde: los cinco más próximos a '+point.name+'.">'+grid+dots+selected+'<path d="M'+(x(point.lon)-5)+' '+y(point.lat)+'h10 M'+x(point.lon)+' '+(y(point.lat)-5)+'v10" stroke="white" stroke-width="2"/><text x="'+(x(point.lon)-10)+'" y="'+(y(point.lat)+18)+'" text-anchor="end" style="fill:white">'+point.name+'</text><text x="525" y="226" text-anchor="end">Longitud · latitud · vista regional</text></svg>';
 }
 function quakes(){const point=cities[$('#quake-city').value],nearest=QUAKE_MATH.nearest(catalog.features,point);plot(nearest,point);$('#quake-table').innerHTML='<table class="evidence-table"><caption class="sr-only">Cinco eventos más próximos a '+point.name+' en el catálogo archivado</caption><thead><tr><th>ID USGS</th><th>Mag.</th><th>Prof. km</th><th>Dist. km</th></tr></thead><tbody>'+nearest.map(e=>'<tr><td title="'+escape(e.place)+'">'+escape(e.id)+'</td><td>'+e.mag.toFixed(1)+'</td><td>'+(Number.isFinite(e.depth)?e.depth.toFixed(1):'—')+'</td><td>'+e.distance.toFixed(1)+'</td></tr>').join('')+'</tbody></table>';}
 $('#quake-city').onchange=()=>{if(catalog)quakes();};
 Promise.all(['usgs-m45-month.geojson','sources.json'].map(file=>fetch(dataRoot+file).then(r=>{if(!r.ok)throw Error('No se pudo cargar '+file);return r.json();}))).then(([data,provenance])=>{catalog=data;quakes();$('#quake-provenance').textContent='USGS · '+data.features.length+' eventos M4.5+ · captura '+new Date(provenance.retrieved_at).toISOString().slice(0,16).replace('T',' ')+' UTC · Haversine, R = 6371 km.';}).catch(()=>{$('#quake-table').innerHTML='No se pudo cargar el snapshot. <a href="'+dataRoot+'usgs-m45-month.geojson">Abrir los datos originales ↗</a>';});
})();
