'use strict';
window.COURSE_RESOURCES=[
 {id:'llm',group:'Fundamentos',title:'LLM Course',publisher:'Hugging Face',icon:'🤗',url:'https://huggingface.co/learn/llm-course/chapter1/1',description:'Base para entender modelos de lenguaje, Transformers y sus aplicaciones.',purpose:'Volver a los conceptos después de la primera sesión.'},
 {id:'agents-course',group:'Fundamentos',title:'AI Agents Course',publisher:'Hugging Face',icon:'🤗',url:'https://huggingface.co/learn/agents-course/en/unit0/introduction',description:'Curso de agentes con conceptos, herramientas y ejercicios.',purpose:'Ampliar la práctica con un recorrido guiado.'},
 {id:'patterns',group:'Fundamentos',title:'Building effective agents',publisher:'Anthropic',logo:'claude.png',url:'https://www.anthropic.com/engineering/building-effective-agents',description:'Patrones para distinguir workflows, agentes y uso de herramientas.',purpose:'Leer la arquitectura; contrastar el tooling con las docs actuales.'},
 {id:'opencode',group:'Trabajo con agentes',title:'OpenCode Docs',publisher:'OpenCode',logo:'opencode.png',url:'https://opencode.ai/docs/',description:'Instalación, modelos, herramientas, permisos y configuración.',purpose:'Resolver dudas del entorno que usaremos en clase.'},
 {id:'claude-practice',group:'Trabajo con agentes',title:'Best practices for Claude Code',publisher:'Anthropic',logo:'claude.png',url:'https://code.claude.com/docs/en/best-practices',description:'Cómo dar contexto, preparar el entorno y verificar el resultado.',purpose:'Llevar mejores criterios a tus sesiones con agentes.'},
 {id:'prompting',group:'Trabajo con agentes',title:'Prompting',publisher:'OpenAI Docs',logo:'openai.svg',url:'https://learn.chatgpt.com/docs/prompting',description:'Objetivo, contexto, resultado esperado y límites de una tarea.',purpose:'Formular un pedido que se pueda ejecutar y comprobar.'},
 {id:'harness',group:'Trabajo con agentes',title:'Effective harnesses for long-running agents',publisher:'Anthropic',logo:'claude.png',url:'https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents',description:'Entorno y continuidad para tareas que necesitan varias iteraciones.',purpose:'Profundizar en el arnés después de la demo.'},
 {id:'mcp',group:'Trabajo con agentes',title:'Model Context Protocol',publisher:'Proyecto MCP',icon:'↔',url:'https://modelcontextprotocol.io/docs/getting-started/intro',description:'Protocolo para conectar aplicaciones de IA con datos y herramientas.',purpose:'Entender una opción de integración; no hace falta para esta demo.'},
 {id:'aa',group:'Modelos y costes',title:'Artificial Analysis',publisher:'Artificial Analysis',logo:'artificialanalysis.ico',url:'https://artificialanalysis.ai/',description:'Comparaciones de capacidad, velocidad y coste por tarea.',purpose:'Elegir candidatos y probarlos con tu propio problema.'},
 {id:'models',group:'Modelos y costes',title:'Models.dev',publisher:'Models.dev',logo:'models.svg',url:'https://models.dev/',description:'Catálogo de modelos, proveedores y características.',purpose:'Comprobar qué ofrece cada proveedor y cómo acceder.'},
 {id:'zen',group:'Modelos y costes',title:'OpenCode Zen',publisher:'OpenCode',logo:'opencode.png',url:'https://opencode.ai/docs/zen/',description:'Modelos disponibles, tarifas y condiciones de ofertas gratuitas.',purpose:'Verificar disponibilidad antes de elegir el modelo de clase.'},
 {id:'nasa',group:'Datos y librerías',title:'NASA POWER API',publisher:'NASA',logo:'nasa.png',url:'https://power.larc.nasa.gov/docs/tutorials/service-data-request/api/',description:'Fuente y documentación del recurso solar de nuestra demo.',purpose:'Revisar parámetro, coordenadas, período y unidades.'},
 {id:'pandas',group:'Datos y librerías',title:'pandas Docs',publisher:'pandas',logo:'pandas.svg',url:'https://pandas.pydata.org/docs/',description:'Lectura de datos, agrupación, tablas y cálculos reproducibles.',purpose:'Revisar las operaciones que genera el agente.'},
 {id:'plotly',group:'Datos y librerías',title:'Plotly Python',publisher:'Plotly',logo:'plotly.svg',url:'https://plotly.com/python/',description:'Gráficos interactivos y exportación de visualizaciones.',purpose:'Ampliar la herramienta y comprobar sus ejes y etiquetas.'},
 {id:'usgs',group:'Datos y librerías',title:'USGS GeoJSON feeds',publisher:'USGS',icon:'◎',url:'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',description:'Catálogos de sismos con magnitud, ubicación, tiempo y profundidad.',purpose:'Explorar la alternativa geográfica con sus límites de cobertura.'},
 {id:'frontier',group:'Trabajo con agentes',title:'Rethinking skills and prompts',publisher:'OpenAI Developers',logo:'openai.svg',url:'https://developers.openai.com/blog/rethinking-skills-and-prompts-for-gpt-6-astra',description:'Cambios en las prácticas de trabajo con modelos más capaces.',purpose:'Lectura avanzada: revisar instrucciones y tamaño del contexto.'}
];
